# Linear Algebra

In [21]:
A = rand(1:4,3,3)

3×3 Array{Int64,2}:
 1  1  1
 2  4  3
 1  4  3

In [22]:
B = A
C = copy(A)
[B C]

3×6 Array{Int64,2}:
 1  1  1  1  1  1
 2  4  3  2  4  3
 1  4  3  1  4  3

Solo cambiara B porque esta enlazado a A.

In [23]:
A[1] = 17
[B C]

3×6 Array{Int64,2}:
 17  1  1  1  1  1
  2  4  3  2  4  3
  1  4  3  1  4  3

In [25]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

A es de tipo Array{float64,2} porque es una matriz, en cambio x tiene un tipo Array{float64,1} porque es un vector. En Julia se definen a los Vector{Type} = Array{Type,1} y la matriz{Type}= Array{Type,2}

### Multiplicacion

In [26]:
b = A * x

3-element Array{Float64,1}:
 19.0
  9.0
  8.0

### Transpuesta
Hay diferencia entre A' y A.'

In [28]:
Asym =  A + A'

3×3 Array{Int64,2}:
 34  3  2
  3  8  7
  2  7  6

### Multiplicacion de transpuesta

In [32]:
Apd = A'A

3×3 Array{Int64,2}:
 294  29  26
  29  33  25
  26  25  19

### Resolver sistemas lineales

El problema Ax=b para cuadrado A es resuelto con la función \

In [35]:
A\b

3-element Array{Float64,1}:
 0.9999999999999991
 0.9999999999999556
 1.0000000000000595

### Sistemas sobredeterminados


In [36]:
Atall = A[:,1:2]

3×2 Array{Int64,2}:
 17  1
  2  4
  1  4

In [38]:
display(Atall)

3×2 Array{Int64,2}:
 17  1
  2  4
  1  4

In [39]:
Atall\b

2-element Array{Float64,1}:
 1.0150095925967721
 1.74438550953617

In [40]:
A = randn(3,3)

3×3 Array{Float64,2}:
  0.151575  -0.0277153   0.79683
  0.554187  -0.981361    0.708767
 -1.27724    1.57723    -0.992359

In [42]:
[A[:,1] A[:,1]]\b

2-element Array{Float64,1}:
 -0.5991323902184883
 -0.5991323902184885

### Underdetermined Systems
Cuando A es corta, la funcion devuelve el minimum norm solution

In [43]:
Ashort = A[1:2,:]

2×3 Array{Float64,2}:
 0.151575  -0.0277153  0.79683
 0.554187  -0.981361   0.708767

In [44]:
display(Ashort)

2×3 Array{Float64,2}:
 0.151575  -0.0277153  0.79683
 0.554187  -0.981361   0.708767

In [45]:
Ashort\b[1:2]

3-element Array{Float64,1}:
  0.4929724198087855
  8.47375878809602
 24.045443304937777