# Loops
## While Loops

In [1]:
i=1
while i <= 10
    println(i)
    i+=1
end

1
2
3
4
5
6
7
8
9
10


In [2]:
mis_amigos = ["Zazie","Blue","Capote"]
i=1
while i <=length(mis_amigos)
    amigo = mis_amigos[i]
    println("$amigo es un animalito de 4 patitas")
    i+=1
end

Zazie es un animalito de 4 patitas
Blue es un animalito de 4 patitas
Capote es un animalito de 4 patitas


## For

In [1]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [5]:
mis_amigos = ["Zazie","Blue","Capote"]
for amigo in mis_amigos println("$amigo es mi amigo")end

Zazie es mi amigo
Blue es mi amigo
Capote es mi amigo


### se puede reemplazar "in" con "=" o "∈ "


In [6]:
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [8]:
for i ∈ 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


### Matrices rellenas con la suma del indice de la columna y la fila

In [9]:
m,n = 5,5
A = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [10]:
for i in 1:m
    for j in 1:n
        A[i,j] = i+j
    end
end

In [11]:
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

### Podemos condensar los ciclos anidados

In [12]:
B = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [13]:
for i in 1:m, j in 1:n
    B[i,j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

### The Julia-way

In [14]:
c = [i+j for i in 1:m, j in 1:n]
c

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

### Ahora vamos a embeber un array en un ciclo for, para generar tablas de sumas crecientes

In [18]:
for n in 1:10
    A = [i + j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20